# Generated by Django 4.1.7 on 2023-03-19 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domain',
            name='domain_name',
        ),
        migrations.RemoveField(
            model_name='domain',
            name='project_name',
        ),
        migrations.RemoveField(
            model_name='domain',
            name='purchase_date',
        ),
        migrations.RemoveField(
            model_name='domain',
            name='renewal_alerts',
        ),
        migrations.RemoveField(
            model_name='domain',
            name='renewal_date',
        ),
        migrations.RemoveField(
            model_name='hosting',
            name='hosting_name',
        ),
        migrations.RemoveField(
            model_name='hosting',
            name='project_name',
        ),
        migrations.RemoveField(
            model_name='hosting',
            name='purchase_date',
        ),
        migrations.RemoveField(
            model_name='hosting',
            name='renewal_alerts',
        ),
        migrations.RemoveField(
            model_name='hosting',
            name='renewal_date',
        ),
        migrations.AddField(
            model_name='domain',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='domain',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hosting',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='hosting',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='HostingDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hosting_type', models.CharField(choices=[('own', 'Own'), ('client', 'Client')], default='own', max_length=10)),
                ('project_name', models.CharField(max_length=100)),
                ('purchase_date', models.DateField()),
                ('renewal_date', models.DateField()),
                ('renewal_alerts', models.IntegerField()),
                ('hosting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appone.hosting')),
            ],
        ),
        migrations.CreateModel(
            name='DomainDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_type', models.CharField(choices=[('own', 'Own'), ('client', 'Client')], default='own', max_length=10)),
                ('domain_name', models.CharField(max_length=100)),
                ('purchase_date', models.DateField()),
                ('renewal_date', models.DateField()),
                ('renewal_alerts', models.IntegerField()),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appone.domain')),
            ],
        ),
    ]
