# Generated by Django 4.1.7 on 2023-03-19 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0002_remove_domain_domain_name_remove_domain_project_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hosting',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
