# Generated by Django 4.1.7 on 2023-03-28 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0005_alter_domain_domain_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='due_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='domain',
            name='registered_date',
            field=models.DateField(),
        ),
    ]
