# Generated by Django 4.1.7 on 2023-03-28 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('own', 'Own'), ('client', 'Client')], default='own', max_length=6)),
                ('title', models.CharField(default=None, max_length=255)),
                ('site', models.CharField(default=None, max_length=255)),
                ('purchased_date', models.DateField(default=None)),
                ('renewal_date', models.DateField(default=None)),
                ('website_hosting', models.CharField(choices=[('list1', 'List 1'), ('list2', 'List 2'), ('list3', 'List 3')], default=None, max_length=255)),
                ('domain_purchased', models.CharField(choices=[('list1', 'List 1'), ('list2', 'List 2'), ('list3', 'List 3')], default=None, max_length=255)),
                ('dns_transferred_from', models.CharField(default=None, max_length=255)),
                ('hosting_account', models.EmailField(default=None, max_length=254)),
                ('notify', models.EmailField(default=None, max_length=254)),
            ],
        ),
    ]
