# Generated by Django 4.1.7 on 2023-03-28 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apphost', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hosting',
            name='domain_purchased',
            field=models.CharField(choices=[('fastcomet', 'Fastcomet'), ('hostinger', 'Hostinger'), ('godaddy', 'Godaddy')], default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='hosting',
            name='site',
            field=models.CharField(choices=[('static', 'Static'), ('dynamic', 'Dynamic'), ('ecommerce', 'Ecommerce')], default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='hosting',
            name='website_hosting',
            field=models.CharField(choices=[('fastcomet', 'Fastcomet'), ('hostinger', 'Hostinger'), ('godaddy', 'Godaddy')], default=None, max_length=255),
        ),
    ]
