# Generated by Django 4.1.7 on 2023-03-28 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apphost', '0002_alter_hosting_domain_purchased_alter_hosting_site_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hosting',
            name='hosting_account',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
