# Generated by Django 4.1.7 on 2023-03-28 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apphost', '0003_alter_hosting_hosting_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hosting',
            name='notify',
            field=models.CharField(max_length=255),
        ),
    ]
